# Generated by Django 5.1.2 on 2024-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_employee_position_remove_department_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
