# Generated by Django 5.1.2 on 2024-11-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='assigned_projects', to='Myapp.employee'),
        ),
    ]
